"use client";

import { useEffect, useMemo, useState } from "react";
import Image from "next/image";
import ContactForm from "@/components/ContactForm";
import LampPullCord from "@/components/LampPullCord";
import VibeCodingTag from "@/components/VibeCodingTag";
import YearBook from "@/components/YearBook";
import GameLibrary from "@/components/GameLibrary";
import pinkme from "../../pinkme.jpeg";
import me1 from "../../me_1.jpg";
import me2 from "../../me_2.jpg";
import teacher from "../../teacher.jpg";
import company from "../../company.jpg";
import project1 from "../../project1.png";
import project2 from "../../project2.png";

type PageKey = "home" | "education" | "internship" | "projects" | "museum" | "contact";
const navItems: { key: PageKey; label: string }[] = [
  { key: "home", label: "Home" },
  { key: "education", label: "Education" },
  { key: "internship", label: "Internship" },
  { key: "projects", label: "Projects" },
  { key: "museum", label: "My Curated World" },
  { key: "contact", label: "Contact" },
];
function playClickSound() { const c = new window.AudioContext(); const o1 = c.createOscillator(); const o2 = c.createOscillator(); const g = c.createGain(); o1.type = "square"; o2.type = "square"; o1.frequency.value = 920; o2.frequency.value = 1240; o1.connect(g); o2.connect(g); g.connect(c.destination); g.gain.value = 0.045; o1.start(); o2.start(c.currentTime + 0.03); o1.stop(c.currentTime + 0.08); o2.stop(c.currentTime + 0.12); }

export default function PortfolioShell() {
  const [loading, setLoading] = useState(true);
  const [theme, setTheme] = useState<"light" | "dark">("light");
  const [activePage, setActivePage] = useState<PageKey>("home");
  const [displayPage, setDisplayPage] = useState<PageKey>("home");
  const [isPageTransitioning, setIsPageTransitioning] = useState(false);
  const [eduStage, setEduStage] = useState<"master" | "bachelor" | null>(null);
  const [internStage, setInternStage] = useState<"hz" | "xs" | null>(null);
  const [projectStage, setProjectStage] = useState<"chem" | "inno" | null>(null);
  const pageTitle = useMemo(() => navItems.find((i) => i.key === displayPage)?.label, [displayPage]);
  const toggleTheme = () => setTheme((t) => (t === "light" ? "dark" : "light"));
  const switchPage = (nextPage: PageKey) => { if (nextPage === activePage || isPageTransitioning) return; setActivePage(nextPage); setIsPageTransitioning(true); window.setTimeout(() => { setDisplayPage(nextPage); setIsPageTransitioning(false); }, 260); };
  useEffect(() => { const t = window.setTimeout(() => { try { playClickSound(); } catch {} setLoading(false); }, 120); return () => window.clearTimeout(t); }, []);

  return <div className="site-wrap" data-theme={theme}>{loading ? <div className="loading-mask"><div className="loading-core"><p className="loading-text">loading...</p><Image className="pixel-mouse" src="/pixel-mouse.svg" alt="pixel mouse" width={52} height={52} /><div className="loading-bar" aria-hidden="true"><span /></div></div></div> : null}<header className="top-nav"><nav><div className="nav-left" aria-hidden="true"><span className="nav-coconut">🥥</span><span className="nav-welcome">welcome to soaringfish’s peronal space</span></div><div className="nav-chip-list">{navItems.map((item) => <button key={item.key} type="button" className={`brand-time-chip nav-chip ${activePage === item.key ? "is-active" : ""}`} onClick={() => switchPage(item.key)}>{item.label}</button>)}</div></nav></header><div className="lamp-contact-row"><div className="lamp-spacer" /><div className="lamp-anchor"><LampPullCord theme={theme} onToggleTheme={toggleTheme} /></div></div><main className="main-container single-page"><section className={`section page-scene ${isPageTransitioning ? "page-out" : "page-in"} ${displayPage === "education" || displayPage === "internship" || displayPage === "projects" ? "section-brand-wrap" : ""} ${displayPage === "museum" ? "museum-section" : ""} ${displayPage === "contact" ? "contact-page-section" : ""}`}>{displayPage === "museum" ? <h2 className="section-title museum-title">{pageTitle}</h2> : null}{displayPage === "contact" ? <h2 className="section-title contact-page-title">联系我</h2> : null}

{displayPage === "home" ? <div className="home-layout"><div className="profile-card"><div className="photo-wrap"><Image src={pinkme} alt="个人照片" className="main-photo" loading="eager" /><span className="home-badge badge-a">sweet orbit</span><span className="home-badge badge-b">daily sparkle</span></div></div><div className="home-copy"><div className="home-decor" aria-hidden="true"><span className="home-decor-dot d1" /><span className="home-decor-dot d2" /><span className="home-decor-stroke s1" /><span className="home-decor-stroke s2" /><span className="home-star st1">✦</span><span className="home-star st2">✦</span><span className="home-ring" /></div><div className="tag-wrap over-title"><span className="float-tag">dacing</span><span className="float-tag float-tag-weaving">Weaving</span><span className="float-tag">reading</span><span className="float-tag float-tag-vibe"><VibeCodingTag /></span></div><h1>Know about me</h1><p>在每个新机遇中寻找更多发掘自我的机会</p><p className="paw-line">生活就是生活，每一步都希望有迹可循<Image src="/cat-paw.svg" alt="猫咪小脚印" width={24} height={24} /></p><p>欣赏美，珍惜美，追求美的飞飞鱼</p><div className="home-mini-panels"><div className="home-mini-card">记录灵感</div><div className="home-mini-card">缓慢成长</div><div className="home-mini-card">保持心动</div></div></div></div> : null}

{displayPage === "education" ? <div className="brand-page"><p className="brand-kicker">Education</p><h2 className="brand-page-title">Education</h2><div className="brand-duo"><div className={`brand-col brand-col-master ${eduStage === "master" ? "is-open" : ""}`}><div className="brand-col-head"><span className="brand-tag brand-tag-uni">浙江大学（985） 科学与技术教育（硕士）</span><button type="button" className={`brand-time-chip ${eduStage === "master" ? "is-active" : ""}`} onClick={() => setEduStage((p) => (p === "master" ? null : "master"))}>2024.09-2027.06</button></div>{eduStage === "master" ? <><h3 className="brand-col-title brand-col-title-light-on-dark">浙江大学（985）</h3><p className="brand-col-sub">科学与技术教育（硕士）</p><div className="brand-body-visible"><div className="brand-module"><h4 className="brand-module-title">主修课程</h4><ul className="brand-kw-list"><li>科技教育前沿专题</li><li>心理发展与教育</li><li>科学教育导论</li><li>信息技术与科学传播导论</li><li>科学与技术教育教学设计与实施</li><li>人工智能在教育上的应用</li></ul></div><div className="brand-module"><h4 className="brand-module-title">论文发表</h4><p className="brand-snippet">第一作者身份发表教育游戏教学模式相关论文至《上海教育科研》期刊。</p></div><div className="brand-module"><h4 className="brand-module-title">荣誉奖项</h4><ul className="brand-kw-list brand-kw-list-inline awards-inline-dark-fix"><li>全国“田家炳杯”科学与技术教育专业全日制教育硕士专业学位研究生教学技能大赛三等奖</li><li>一等奖学金（校级）</li><li>优秀研究生（校级）</li><li>五好研究生（校级）</li></ul></div></div></> : <p className="brand-hint brand-hint-collapsed">点击时间标签展开内容</p>}<div className="brand-geo brand-geo-lavender"><div className="brand-geo-shape" aria-hidden="true" /><Image src={me1} alt="硕士阶段" className="brand-geo-photo" /></div></div><div className={`brand-col brand-col-bachelor ${eduStage === "bachelor" ? "is-open" : ""}`}><div className="brand-col-head"><span className="brand-tag brand-tag-sage brand-tag-uni">湖南师范大学（211） 化学师范（本科）</span><button type="button" className={`brand-time-chip ${eduStage === "bachelor" ? "is-active" : ""}`} onClick={() => setEduStage((p) => (p === "bachelor" ? null : "bachelor"))}>2020.09-2024.06</button></div>{eduStage === "bachelor" ? <><h3 className="brand-col-title brand-col-title-light-on-dark">湖南师范大学（211）</h3><p className="brand-col-sub">化学师范（本科）</p><div className="brand-body-visible"><div className="brand-module"><h4 className="brand-module-title">GPA</h4><p className="brand-snippet brand-snippet-strong">GPA：4.18/5（前3%）</p></div><div className="brand-module"><h4 className="brand-module-title">校园奖项</h4><ul className="brand-kw-list brand-kw-list-inline awards-inline-dark-fix"><li>校优秀毕业生</li><li>优秀学生干部</li><li>综合二等奖学金</li><li>百优共青团员</li><li>十佳共青团干部</li></ul></div></div></> : <p className="brand-hint brand-hint-collapsed">点击时间标签展开内容</p>}<div className="brand-geo brand-geo-sage"><div className="brand-geo-shape" aria-hidden="true" /><Image src={me2} alt="本科阶段" className="brand-geo-photo" /></div></div></div></div> : null}

{displayPage === "internship" ? <div className="brand-page"><p className="brand-kicker">Internship</p><h2 className="brand-page-title">Internship</h2><div className="brand-duo"><div className={`brand-col brand-col-intern-a ${internStage === "hz" ? "is-open" : ""}`}><div className="brand-col-head"><span className="brand-tag">浙江省杭州第二中学 高中化学教师</span><button type="button" className={`brand-time-chip ${internStage === "hz" ? "is-active" : ""}`} onClick={() => setInternStage((p) => (p === "hz" ? null : "hz"))}>2026.03-2026.07</button></div>{internStage === "hz" ? <><h3 className="brand-col-title brand-col-title-light-on-dark">浙江省杭州第二中学</h3><p className="brand-col-sub">高中化学教师</p><div className="brand-body-visible"><div className="brand-module"><h4 className="brand-module-title">概述</h4><p className="brand-snippet">负责高三年级化学教学支持工作，围绕学生学习需求参与教学内容准备、课堂组织与课后答疑。</p></div></div></> : <p className="brand-hint brand-hint-collapsed">点击时间标签展开内容</p>}<div className="brand-geo brand-geo-mist"><div className="brand-geo-shape" aria-hidden="true" /><Image src={teacher} alt="教学实习" className="brand-geo-photo" /></div></div><div className={`brand-col brand-col-intern-b ${internStage === "xs" ? "is-open" : ""}`}><div className="brand-col-head"><span className="brand-tag brand-tag-sage">杭州小事做好教育科技有限公司 AI教育课程设计实习生</span><button type="button" className={`brand-time-chip ${internStage === "xs" ? "is-active" : ""}`} onClick={() => setInternStage((p) => (p === "xs" ? null : "xs"))}>2025.06-2025.09</button></div>{internStage === "xs" ? <><h3 className="brand-col-title brand-col-title-light-on-dark">杭州小事做好教育科技有限公司</h3><p className="brand-col-sub">AI教育课程设计实习生</p><div className="brand-body-visible"><div className="brand-module"><h4 className="brand-module-title">概述</h4><p className="brand-snippet">参与中小学 AI 创客教育课程内容策划与迭代，围绕目标用户需求协助完成课程框架搭建、内容筛选与整合，提升课程内容的系统性与用户接受度。</p></div><div className="brand-module-grid brand-module-grid-vertical"><div className="brand-mini-card brand-mini-card-gradient"><h4 className="brand-mini-title">课程内容研发与迭代</h4><p>独立负责《趣帆 AI 创客教育》系列 4 课时课程讲义撰写，深度参与说课及两轮磨课，根据反馈持续优化课程逻辑、互动设计和表达方式，推动课程高质量交付。</p></div><div className="brand-mini-card brand-mini-card-gradient"><h4 className="brand-mini-title">线上品牌推广</h4><p>协助策划并主持 2 场 AI 科普主题线上直播，累计吸引近 400 人次观看；直播过程中收集约 10 条用户反馈，并针对内容节奏、讲解表达和互动形式进行复盘优化，后续传播效果有所提升。</p></div><div className="brand-mini-card brand-mini-card-gradient"><h4 className="brand-mini-title">线下活动策划与执行</h4><p>以核心成员身份协助策划并执行 1 场大型 AI 科普讲座与 1 场主题游园会，负责活动流程支持、现场协调与执行推进，提升活动参与体验和线下传播效果。</p></div></div></div></> : <p className="brand-hint brand-hint-collapsed">点击时间标签展开内容</p>}<div className="brand-geo brand-geo-dusk"><div className="brand-geo-shape" aria-hidden="true" /><Image src={company} alt="企业实习" className="brand-geo-photo" /></div></div></div></div> : null}

{displayPage === "projects" ? <div className="brand-page"><p className="brand-kicker">Projects</p><h2 className="brand-page-title">Projects</h2><div className="brand-duo"><div className={`brand-col brand-col-project-a ${projectStage === "chem" ? "is-open" : ""}`}><div className="brand-col-head"><span className="brand-tag">“微瑞杯”第四届全国大学生化学实验创新设计大赛国家一等奖 负责人</span><button type="button" className={`brand-time-chip ${projectStage === "chem" ? "is-active" : ""}`} onClick={() => setProjectStage((p) => (p === "chem" ? null : "chem"))}>2023.08</button></div>{projectStage === "chem" ? <><h3 className="brand-col-title brand-col-title-light-on-dark">“微瑞杯”第四届全国大学生化学实验创新设计大赛</h3><p className="brand-col-sub">国家一等奖 · 负责人</p><div className="brand-body-visible"><div className="brand-module"><h4 className="brand-module-title">项目概述</h4><p className="brand-snippet">负责项目整体方案设计与推进，围绕“活色生相”理念将前沿科技成果转化为综合化学实验方案；主导项目内容策划、实验逻辑梳理与成果展示设计，协调团队分工并推动项目落地，最终获得国家一等奖。</p></div></div></> : <p className="brand-hint brand-hint-collapsed">点击时间标签展开内容</p>}<div className="brand-geo brand-geo-project-a"><div className="brand-geo-shape" aria-hidden="true" /><Image src={project1} alt="项目一" className="brand-geo-photo brand-geo-photo-project" /></div></div><div className={`brand-col brand-col-project-b ${projectStage === "inno" ? "is-open" : ""}`}><div className="brand-col-head"><span className="brand-tag brand-tag-sage">省级大创：《偶氮分子功能化聚酯基无墨循环可擦写纸张》</span><button type="button" className={`brand-time-chip ${projectStage === "inno" ? "is-active" : ""}`} onClick={() => setProjectStage((p) => (p === "inno" ? null : "inno"))}>2023.05-2024.06</button></div>{projectStage === "inno" ? <><h3 className="brand-col-title brand-col-title-light-on-dark">省级大创</h3><p className="brand-col-sub">《偶氮分子功能化聚酯基无墨循环可擦写纸张》</p><div className="brand-body-visible"><div className="brand-module"><h4 className="brand-module-title">项目概述</h4><p className="brand-snippet">参与项目资料调研、实验支持与阶段性成果整理，协助推进项目从研究思路到成果输出的全过程；结合实验效果与应用场景进行分析整理。</p></div></div></> : <p className="brand-hint brand-hint-collapsed">点击时间标签展开内容</p>}<div className="brand-geo brand-geo-project-b"><div className="brand-geo-shape" aria-hidden="true" /><Image src={project2} alt="项目二" className="brand-geo-photo brand-geo-photo-project" /></div></div></div></div> : null}

{displayPage === "museum" ? <div className="museum-stack"><div className="museum-block museum-library-block"><YearBook /></div><div className="museum-block museum-game-block"><GameLibrary /></div></div> : null}
{displayPage === "contact" ? <ContactForm /> : null}
</section></main></div>;
}